#Gimmicks Config

## Teams - depends on TagAPI
# enabled (boolean)		= enables teams with coloured name tags
# resetondeath (boolean)= players leave team on death

teams:
  enabled: true
  resetondeath: false

## Face Death Messages
# enabled (boolean) 	= show player faces in chat on death
facedeathmessages:
  enabled: true

## Hunger Compass
# enabled (boolean) 	= enables tracking compass
# range (double) 		= max range to track players
# showplayer (boolean) 	= show name of player being tracked

hungercompass:
  enabled: false
  range: 500.0
  showplayer: false
  
  
## Magic Chests
# enabled (boolean) = enables magicchest
# respawn (int) = time in seconds before chests restock

magicchests:
  enabled: false
  respawn: 300