name: Gimmicks
author: TeaJizzle
version: 0.1
main: com.gimmicknetwork.gimmicks.gimmicks

commands:
  team:
    description: "Set team colour."
    usage: "Usage: /team <colour> (Colours red, blue, green, gold, aqua, purple)"
    permission: gimmicks.teams.use
  teamtp:
    description: "TP team to your location"
    usage: "Usage: /teamtp <colour> (Colours red, blue, green, gold, aqua, purple)"
    permission: gimmicks.teams.admin


permissions:
  gimmicks.teams.use:
    description: "use team colours"
    default: false
  gimmicks.teams.admin:
    description: "admin team colours"
    default: false