name: Gimmicks
author: TeaJizzle
version: 0.1.9
main: com.gimmicknetwork.gimmicks.Gimmick

depends: [TagAPI]

commands:
  spreadall:
    description: "Spreads all players"
    usage: "Usage: /spreadplayers <x> <z> <spreadDistance> <maxRange>"
    permission: gimmicks.admin
  gimmicks:
    description: "Reload Gimmicks config."
    usage: "Usage: /gimmicks reload"
    permission: gimmicks.admin
  team:
    description: "Set team colour."
    usage: "Usage: /team <colour> (Colours red, blue, green, gold, aqua, purple)"
    permission: gimmicks.teams.use
  teamtp:
    description: "TP team to your location"
    usage: "Usage: /teamtp <colour> (Colours red, blue, green, gold, aqua, purple)"
    permission: gimmicks.teams.admin
  teamsetspawn:
    description: "Set team spawn"
    usage: "Usage: /teamsetspawn <colour> (Colours red, blue, green, gold, aqua, purple)"
    permission: gimmicks.teams.admin
  setchest:
    description: "Set magic chest"
    usage: "Usage: /setchest while looking at a chest"
    permission: gimmicks.admin
  setloot:
    description: "Set loot"
    usage: "Usage: /setloot while looking at a chest"
    permission: gimmicks.admin  
  muteall:
    description: "Toggle global mute"
    usage: "Usage: /muteall"
    permission: gimmicks.admin 
  healall:
    description: "Heal and feed all players."
    usage: "Usage: /healall"
    permission: gimmicks.admin
  playintro:
    description: "Play hunger games introduction."
    usage: "Usage: /playinfo"
    permission: gimmicks.admin  


permissions:
  gimmicks.teams.use:
    description: "use team colours"
    default: false
  gimmicks.teams.admin:
    description: "admin team colours"
    default: false
  gimmicks.admin:
    description: "gimmicks admin"
    default: false